blog/apps/noticias/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^crear_pagina/$', views.crear_pagina, name='crear_pagina'),
    url(r'^ver-pagina/(?P<pk>\d+)/$', views.ver_pagina, name='ver_pagina'),
    url(r'^listado_paginas/$', views.listado_paginas, name='listado_paginas'),
]

blog/apps/usuarios/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^registro/$', views.RegistroCreate.as_view(), name='registro'),

    url(r'^ingresar/$', views.ingresar, name='ingresar'),
]

blog/settings/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('apps.noticias.urls', namespace='noticia')),
    url(r'', include('apps.usuarios.urls', namespace='usuario')),
]

blog/apps/comentarios/models.py
from django.db import models
from apps.noticias.models import Noticia


class Comentario(models.Model):
    noticia = models.ForeignKey(Noticia)
    nombre = models.CharField(max_length=120)
    comentario = models.TextField()

    class Meta:
        verbose_name = "Noticia"
        verbose_name_plural = "Noticias"

    def __str__(self):
        return self.nombre

blog/apps/noticias/models.py
from django.db import models
from django.core.urlresolvers import reverse
from apps.usuarios.models import Usuario


class CategoriaNoticia(models.Model):
    nombre = models.CharField(max_length=120)

    class Meta:
        verbose_name = "Categoria Noticia"
        verbose_name_plural = "Categoria Noticias"

    def __str__(self):
        return self.nombre


class Noticia(models.Model):
    usuario = models.ForeignKey(Usuario)
    titulo = models.CharField(max_length=120)
    contenido = models.TextField()
    categoria = models.ForeignKey(CategoriaNoticia)

    class Meta:
        verbose_name = "Noticia"
        verbose_name_plural = "Noticias"

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('noticia:ver_pagina', kwargs={'pk': self.pk})

blog/apps/usuarios/models.py
# -*- coding: utf-8 -*-
from django.db import models


class Usuario(models.Model):
    last_login = models.DateTimeField('Último Login', blank=True, null=True)
    usuario = models.CharField("usuario", max_length=120, unique=True)
    email = models.EmailField(max_length=60, unique=True, db_index=True, blank=True)
    password = models.CharField(max_length=64, verbose_name='Contraseña')
    estado = models.BooleanField("Estado", default=True)

    class Meta:
        ordering = ['usuario']

    def __unicode__(self):
        return self.usuario

    def is_authenticated(self):
        return True

    @property
    def is_staff(self):
        return False

blog/apps/noticias/forms.py
# -*- coding: utf-8 -*-
from .models import Noticia
from django import forms


class NoticiaForm(forms.ModelForm):
    class Meta:
        model = Noticia
        fields = ['contenido', 'titulo', 'categoria', 'usuario']

blog/apps/usuarios/forms.py
# -*- coding: utf-8 -*-
from django.contrib.auth import authenticate
from .models import Usuario
from django import forms


class IngresarForm(forms.Form):
    usuario = forms.CharField(label='usuario')
    password = forms.CharField(label='Contraseña')

    def clean_usuario(self):
        usuario = self.cleaned_data['usuario']
        try:
            Usuario.objects.get(usuario=usuario)
        except Usuario.DoesNotExist:
            mensaje = "El usuario no ha sido registado"
            raise forms.ValidationError(mensaje)
        return usuario

    def auth(self):
        cd = self.cleaned_data
        return authenticate(username=cd['usuario'], password=cd['password'])

blog/apps/comentarios/views.py
from django.shortcuts import render

# Create your views here.

blog/apps/noticias/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template import RequestContext as ctx
from django.contrib.sessions.models import Session
from django.core.urlresolvers import reverse, reverse_lazy
from .models import Noticia
from .forms import NoticiaForm
from django.contrib.auth.decorators import login_required
import redis
import json


def home(request):
    noticias = Noticia.objects.all()
    return render_to_response('portal/home.html', locals(), context_instance=ctx(request))


def listado_paginas(request):
    ''' Vista para mostrar la tabla de las entradas creadas'''
    noticias = Noticia.objects.all()
    return render_to_response('portal/listado-pagina.html', locals(), context_instance=ctx(request))


@login_required(login_url=reverse_lazy('usuario:ingresar'))
def crear_pagina(request):
    ''' Vista para crear un entradas'''
    r = redis.StrictRedis(host='localhost', port=6379, db=0)
    # form_json = {
    #     'titulo': form.cleaned_data.get('titulo'),
    #     'contenido': form.cleaned_data.get('contenido')
    # }

    if request.method == "POST":
        form = NoticiaForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            form_json = {
                'titulo': form.cleaned_data.get('titulo'),
                'contenido': form.cleaned_data.get('contenido')
            }
            r.publish('mundo', json.dumps(form_json))
            return redirect(reverse_lazy('noticia:listado_paginas'))
    else:
        form = NoticiaForm()
    return render_to_response('portal/crear-pagina.html', locals(), context_instance=ctx(request))


def ver_pagina(request, pk):
    ''' Vista ver el detalle de una pagina'''
    noticia = get_object_or_404(Noticia, pk=pk)
    return render_to_response('portal/ver-pagina.html', locals(), context_instance=ctx(request))

blog/apps/usuarios/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import get_object_or_404, render_to_response, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.template import RequestContext as ctx
from django.views.generic import CreateView
from django.core.urlresolvers import reverse, reverse_lazy
from django.utils import timezone
from django.contrib import messages
from .models import Usuario
from .forms import IngresarForm
from apps.noticias.models import Noticia


class RegistroCreate(CreateView):
    ''' Vista para registrar usuario, se uso vistas basadas en clases '''
    model = Usuario
    fields = ['usuario', 'password', 'email']
    template_name = 'portal/registro.html'
    success_url = reverse_lazy('usuario:ingresar')


def ingresar(request):
    ''' Vista de login '''
    if request.method == "POST":
        form = IngresarForm(request.POST)
        if form.is_valid():
            user = form.auth()
            if user is not None:
                if user.estado:
                    user.last_login = timezone.now()
                    user.save()
                    login(request, user)
                    return redirect(reverse('noticia:crear_pagina'))
                else:
                    messages.add_message(request, messages.WARNING, 'Usuario no se encuentra registrado')
            else:
                messages.add_message(request, messages.WARNING, u'El email y contraseña son inválidos')
    else:
        form = IngresarForm()

    return render_to_response('portal/login.html', locals(), context_instance=ctx(request))

blog/templates/common/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Vounty</title>
  <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <link href="{% static 'css/zeus.css' %}" rel="stylesheet" type="text/css" />
  {% block css %}

  {% endblock css %}
</head>
<body>
  <div class="wrapper">
    {% include "common/header.html" %}
    {% block content %}

    {% endblock content %}
    {% include "common/footer.html" %}
  </div>

<script src="{% static 'js/jQuery-2.1.4.min.js' %}" type="text/javascript"></script>

<script src="{% static 'js/zeus.js' %}" type="text/javascript"></script>
{% block js %}

{% endblock js %}
</body>
</html>

blog/templates/common/footer.html
<footer>

</footer>

blog/templates/common/header.html
<header>
	<div class="wancho">
		<h1 class="titulo-principal">
			Portal de Noticias
		</h1>
		<nav class="nav-login">
			{% if request.user.is_authenticated %}
					<a href="">{{request.user.email}}</a>
					<a href="">Salir</a>
			{% endif %}
			{% if not request.user.is_authenticated %}
			<a href="{% url 'usuario:ingresar' %}">Login</a>
			{% endif %}
			<a href="{% url 'usuario:registro' %}">Registro</a>

		</nav>
	</div>

</header>

blog/templates/portal/categorias.html
{% extends 'common/base.html' %}

{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.domenu-0.13.37.css' %}"/>
{% endblock css %}
{% block content %}
<style>
        .cf:after {
            visibility: hidden;
            display: block;
            font-size: 0;
            content: " ";
            clear: both;
            height: 0;
        }

        * html .cf {zoom: 1;}

        *:first-child+html .cf {zoom: 1;}

        html {
            margin: 0;
            padding: 0;
        }

        body {
            font-size: 100%;
            margin: 0;
            padding: 1.75em;
            font-family: 'Helvetica Neue', Arial, sans-serif;
        }

        h1 {
            font-size: 1.75em;
            margin: 0 0 0.6em 0;
        }

        a {color: #2996cc;}

        a:hover {text-decoration: none;}

        p {line-height: 1.5em;}

        .small {
            color: #666;
            font-size: 0.875em;
        }
       /* .dd-item:hover{
          cursor: move;
        }*/
        .large {font-size: 1.25em;}
    </style>

<section class="ver-pagina wancho">
  <form action="#" method="POST">
      {% csrf_token %}
      {{form}}
      <button>Enviar</button>
  </form>
  <button type="button"
        class="btn btn-primary btn-lg" data-follow="follow"
        data-target="52cd6196211b6fc26a8b456c">ds</button>
  <br>
  <hr>
  <br>
  <ul class="position-relative">
    <li><h3>test</h3></li>
    {% for categoriaabuelo in categorias_abuelo %}
      {% if not categoriaabuelo.categoria %}
      <li><h3 draggable='true' data-pk={{categoriaabuelo.pk}} class="cat-abuelo">{{categoriaabuelo.nombre}}</h3>
          <ul>
            {% for categoriapadre in categoriaabuelo.mucha_categoria.all %}
              <li><h3 draggable='true' data-pk={{categoriapadre.pk}} class="cat-padre">{{categoriapadre.nombre}}</h3>
                <ul>
                    {% for categoriahijo in categoriapadre.mucha_categoria.all %}
                      <li><h3 draggable='true' data-pk={{categoriahijo.pk}} class="cat-hijo">{{categoriahijo.nombre}}</h3></li>
                    {% endfor %}
                </ul>
              </li>
            {% endfor %}
          </ul>
      </li>
      {% endif %}
    {% endfor %}
    <li>

    </li>
  </ul>

</section>
<section class="gg">
  <div class="dd" id="domenu">
                <button class="dd-new-item ">+</button>
                    <!-- .dd-item-blueprint is a template for all .dd-item's -->
                    <li class="dd-item-blueprint">
                        <div class="dd-handle dd3-handle">Drag</div>
                            <div class="dd3-content dd-handlenew">
                                <span>[item_name]</span>

                                <div class="dd-edit-box" style="display: none;">

                                    <input type="text" name="title" placeholder="Item" data-placeholder="Item {?numeric.increment}" data-default-value="Item {?numeric.increment}">
                                    <select name="superselect">
                                        <option>select something...</option>
                                        <optgroup label="Pages">
                                            <option value="1">http://example.com/page/1</option>
                                            <option value="2">http://example.com/page/2</option>
                                        </optgroup>
                                        <optgroup label="Categories">
                                            <option value="1">News</option>
                                            <option value="2">Stories</option>
                                        </optgroup>
                                    </select>
                                    <i>&#x270e;</i>
                                </div>
                            </div>
                    </li>

                <ol class="dd-list"></ol>
            </div>
            <form>
              <button>Guardar</button>
              <label>

                <input type="text" name="guardar" id="acumulador" style="width:600px; border:1px solid red;">
              </label>
            </form>
</section>

{% endblock content %}
{% block js %}
<script>
  // $("h3").on('dragenter', function(event) {
  //  event.preventDefault();
  //  $(this).addClass('color-red')
  //  console.log(event)
  //  console.log("entro")
  //  var position = $( this ).position();
  //  console.log(position.left)
  //  console.log(position.top)
  //   Act on the event
  // });
  // $("h3").on('dragleave', function(event) {
  //  event.preventDefault();
  //  $(this).removeClass('color-red')
  //  console.log("entrodrasd")
  //  var position = $( this ).position();
  //  console.log(position.top)
  //  /* Act on the event */
  // });
</script>

<script>

    $(document).ready(function()
    {
        var listado_acumulador = []
        var data_categoria = [
        {% for categoria in categorias_abuelo %}
          {"id_padre":"{{categoria.pk}}", "hijos":[{% for cat in categoria.mucha_categoria.all %}{"id_hijo":"{{cat.pk}}"},{% endfor %}]},
        {% endfor %}

        ]
        function actualizar(pk_padre, pk_hijo){

        }
        function acumulador(pk_padre, pk_hijo){
          console.log(typeof(pk_padre))

          // acumulador = JSON.parse(acumulador)
          $.each(data_categoria, function(index, object) {
              if(!pk_padre){
                pk_padre = "no_tiene"
              }

              $.each(object["hijos"], function(posicion, el) {
                if (object["id_padre"]==pk_padre) {
                    if (el["id_hijo"]==pk_hijo) {
                      console.log("no cambio")
                    }
                    else{
                      // console.log(acumulador)
                      // acumulador.push("{hijo:"+pk_hijo+",padre:"+pk_padre+"},")
                      if (listado_acumulador) {
                        listado_acumulador.push({"hijo":pk_hijo,"padre":pk_padre})
                        // acumulador = acumulador + "-[hijo:"+pk_hijo+",padre:"+pk_padre+"]"
                      }
                      else{
                        listado_acumulador.push({"hijo":pk_hijo,"padre":pk_padre})
                      }
                    }
                }
                // else{
                //    if (acumulador) {
                //         acumulador = acumulador + "-[hijo:"+pk_hijo+",padre:"+pk_padre+"]"
                //       }
                //       else{
                //         acumulador = "[hijo:"+pk_hijo+",padre:"+pk_padre+"]"
                //     }
                // }
              });
          });
          // js = JSON.parse(acumulador)

          console.log(listado_acumulador)
          $("#acumulador").val(JSON.stringify(listado_acumulador))

        }

        var updateOutput = function(e)
        {
            var list   = e.length ? e : $(e.target),
                output = list.data('output');
            if (window.JSON) {
                output.val(window.JSON.stringify(list.domenu('serialize')));//, null, 2));
            } else {
                output.val('JSON browser support required for this demo.');
            }
        };

        $('#domenu').domenu({
            maxDepth: 3,
            // handleClass:            'dd-item',
            onDomenuInitialized: [function() {
                // console.log('event: onDomenuInitialized', 'arguments:', arguments, 'context:', this);
            }],
            data: '[{% for catabuelo in categorias_abuelo %}{% if not catabuelo.categoria %}{"id":"{{catabuelo.pk}}", "title":"{{catabuelo.nombre}}" {% if catabuelo.mucha_categoria.all %},"children":[{% for catpadre in catabuelo.mucha_categoria.all %}{"id":"{{catpadre.pk}}","title":"{{catpadre.nombre}}","http":"", "children": [{% for cathijo in catpadre.mucha_categoria.all %}{"id":"{{cathijo.pk}}", "title":"{{cathijo.nombre}}", "http":""}{% if not forloop.last %},{% endif %}{% endfor %}]}{% if forloop.last %}]{% endif %}{% endfor %}{% endif %}}{% if not forloop.last %},{% endif %}{% endif %}{% endfor %}]'
            // data: '[{"id":11,"title":"Item 11","http":""},{"id":10,"title":"Item 10","http":""},{"id":9,"title":"Item 9","http":""},{"id":6,"title":"Home","http":"","children":[{"id":5,"title":"Item 5dsad","http":""},{"id":4,"title":"Item 4","http":"","children":[{"id":3,"title":"Item 3","http":""},{"id":2,"title":"Item 2","http":"","children":[{"id":7,"title":"Example","http":"http://google.com"},{"id":8,"title":"Item 8","http":""}]}]}]},{"id":1,"title":"Item 1","http":""}]'
        }).parseJson()
                .onParseJson(function() {
                    console.log('event: onFromJson', 'arguments:', arguments, 'context:', this);
                })
                .onToJson(function() {
                    console.log('event: onToJson', 'arguments:', arguments, 'context:', this);
                })
                .onSaveEditBoxInput(function() {
                    console.log('event: onSaveEditBoxInput', 'arguments:', arguments, 'context:', this);
                })
                .onItemDrag(function(item_li) {
                    // console.log('event: onItemDrag', 'arguments:', arguments, 'context:', this);
                    //li


                    // var padre = $(item_li['0']).closest('.dd-item').closest('.dd-item').addClass('red')
                    // console.log(padre.addClass('red'))
                })
                .onItemDrop(function(item_li) {
                    // console.log('event: onItemDrop', 'arguments:', arguments, 'context:', this);
                    var pk_hijo = $(item_li['0']).children('.dd3-content').find("input").attr('data-id');
                    var pk_cambiar = $(item_li['0']).closest('.dd-list').closest('.dd-item').children('.dd3-content').css({
                      background: 'red', });
                    var pk_padre = $(item_li['0']).closest('.dd-list').closest('.dd-item').children('.dd3-content').find("input").attr('data-id');
                    console.log(pk_padre)
                    console.log(pk_cambiar)
                    console.log(pk_hijo)
                    acumulador(pk_padre, pk_hijo)

                })
                .onItemAdded(function() {
                    console.log('event: onItemAdded', 'arguments:', arguments, 'context:', this);
                })
                .onItemRemoved(function() {
                    console.log('event: onItemRemoved', 'arguments:', arguments, 'context:', this);
                })
                .onItemStartEdit(function() {
                    console.log('event: onItemStartEdit', 'arguments:', arguments, 'context:', this);
                })
                .onItemEndEdit(function() {
                    console.log('event: onItemEndEdit', 'arguments:', arguments, 'context:', this);
                });



    });
</script>


{% endblock js %}

blog/templates/portal/crear-pagina.html
{% extends 'common/base.html' %}

{% block content %}
	<section class="listado-pagina wancho">

		<div class="cnt-tabla-listado">
			<div class="cnt-registrar-noticia">
				<a href="{% url 'noticia:listado_paginas' %}" class="crear-entrada noticia-lados">
					Cancelar
				</a>

			</div>
			<div class="cnt-formulario" >
				<form action="#" method="POST" clas="form-crear-pagina" enctype="multipart/form-data">
				{% csrf_token %}
					<input type="hidden" name="usuario" value="{{request.user.id}}">
					<ul class="ul-simple">
						<li>
							<label for="">TITULO</label>
							{{form.titulo}}
							{{form.titulo.errors.as_text}}
						</li>
					</ul>
					<ul class="ul-simple">
						<li>
							<label for="">CATEGORIA</label>
							{{form.categoria}}
							{{form.categoria.errors.as_text}}
						</li>
					</ul>

					<ul class="ul-contenido">
						<li>
							<label for="">CONTENIDO</label>
							{{form.contenido}}
							{{form.contenido.errors.as_text}}
						</li>
					</ul>
					<button>Guardar</button>
					{{form.errors}}
				</form>
			</div>
		</div>
	</section>
{% endblock content %}
{% block js %}
<script>
	$(document).ready(function() {

	});
</script>
{% endblock js %}

blog/templates/portal/home.html
{% extends 'common/base.html' %}

{% block content %}
<section class="ver-pagina wancho">
	{% for noticia in noticias %}


	<div class="slide">
		<div class="columna-estado">
			<h2>{{noticia.titulo}}</h2>
		</div>
		<div class="columna-detalle">

			<div class="detalle">
				{{noticia.contenido|truncatechars_html:80}}
			</div>
			<div class="seguir">
				<a href="{{noticia.get_absolute_url}}">Seguir leyendo</a>
			</div>
		</div>
	</div>
	{% endfor %}
</section>


{% endblock content %}
{% block js %}
<script src="{{STATIC_URL}}js/socket.js" type="text/javascript"></script>
<script>
	var socket = io.connect('http://127.0.0.1:3000');

	socket.on("mundo", function(data){
		console.log("-----")
		/*data = String(data)*/
		var data_json = JSON.parse(data)

		html = '<div class="slide"><div class="columna-estado"><h2>'+data_json.titulo+'</h2></div><div class="columna-detalle"><div class="detalle">'+data_json.contenido+'</div><div class="seguir"><a href="{{noticia.get_absolute_url}}">Seguir leyendo</a></div></div></div>'
		$(".ver-pagina").append(html)
	})
</script>
{% endblock js %}

blog/templates/portal/listado-pagina.html
{% extends 'common/base.html' %}

{% block content %}
	<section class="listado-pagina wancho">

		<div class="cnt-tabla-listado">
			<div class="cnt-registrar-noticia">
				<a href="{% url 'noticia:crear_pagina' %}" class="crear-entrada noticia-lados">
					Crear Entrada
				</a>
				<a href="" class="ver-pagina noticia-lados">
					Ver pagina
				</a>
			</div>
			<table>
			  <tr class="cabecera">
			    <td>CODIGO</td>
			    <td>TITULO</td>
			    <td>FECHA</td>
			    <td>ESTADO</td>
			    <td>ACCIONES</td>
			  </tr>
			  {% for noticia in noticias %}


			  <tr class="contenido">
			  	<td>{{noticia.id}}</td>
			    <td>{{noticia.titulo}}</td>
			    <td>{{noticia.fecha}}</td>
			    <td>{{noticia.get_estado_display}}</td>
			    <td class="enlace"><a target="_blank" href="{{noticia.get_absolute_url}}">Ver</a>
							<a target="_blank" href="{{noticia.get_delete_url}}">Eliminar</a>
			    </td>

			  </tr>
			  {% endfor %}
			</table>
		</div>
	</section>
{% endblock content %}

blog/templates/portal/login.html
{% extends 'common/base.html' %}
{% block content %}


	<section class="login wancho">
		<div class="cnt-formulario">
			<h2 class="titulo-secundario">Login</h2>
			<form action="#" method="POST">
			{% csrf_token %}
				<ul>
					<li><input type="text" name="usuario" placeholder="Usuario"></li>
					{{form.usuario.errors.as_text}}
				</ul>
				<ul>
					<li><input type="password" name="password" placeholder="password"></li>
					{{form.password.errors.as_text}}
				</ul>
				<button>Ingresar</button>
				{% if messages %}
          <ul class="messages">
              {% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }} input_errores"{% endif %}>{{ message }}</li>
              {% endfor %}
          </ul>
          {% endif %}
			</form>
		</div>

	</section>

{% endblock content %}

blog/templates/portal/registro.html
{% extends 'common/base.html' %}
{% block content %}


	<section class="login wancho">
		<div class="cnt-formulario">
			<h2 class="titulo-secundario">Registro</h2>
			<form action="#" method="POST">
			{% csrf_token %}
				<ul>
					<li><input type="text" name="usuario" placeholder="Usuario"></li>
					{{form.usuario.errors.as_text}}
				</ul>
				<ul>
					<li><input type="email" name="email" placeholder="email"></li>
					{{form.email.errors.as_text}}
				</ul>
				<ul>
					<li><input type="password" name="password" placeholder="password"></li>

				</ul>
				<button>Ingresar</button>
			</form>
		</div>

	</section>

{% endblock content %}

blog/templates/portal/ver-pagina.html
{% extends 'common/base.html' %}

{% block content %}
<section class="ver-pagina wancho">
	<div class="columna-estado">
		<h2>{{noticia.titulo}}</h2>
		<h3>{{noticia.fecha|date:'d-m-Y'}}</h3>
	</div>
	<div class="columna-detalle">
		<figure>
			<img src="{{noticia.imagen.url}}" alt="">
		</figure>
		<div class="detalle">
			{{noticia.contenido}}
		</div>
	</div>
</section>
{% endblock content %}

blog/templates/pruebas.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>prueba</title>
</head>
<body>
<section>
	<h2>Prueba</h2>
	<ul>
		{% for pr in prueba %}

		<li>{{pr.fecha}}</li>
		<li>{{pr.rango_recha}}</li>
		{% endfor %}
	</ul>
	<form action="">
			{{form}}
	</form>
</section>
</body>
</html>